dist: trusty

language: bash

addons:
    apt_packages:
        - build-essential
        - git
        - curl

cache:
    apt: true
    directories:
        - $HOME/miniconda3_$TRAVIS_OS_NAME/
    timeout: 1000

before_install:
  - bash .travis/travis_before_install.sh


install:
  - export PATH="$HOME/miniconda3_$TRAVIS_OS_NAME/bin:$PATH"
  - echo $PATH
  - bash .travis/travis_install.sh

script:
  - export PATH="$HOME/miniconda3_$TRAVIS_OS_NAME/bin:$PATH"
  - echo $PATH
  - snakemake --use-conda --create-envs-only --conda-prefix "$HOME/miniconda3_$TRAVIS_OS_NAME/envs/"
  - conda clean --all --yes
  - snakemake --use-conda --conda-prefix "$HOME/miniconda3_$TRAVIS_OS_NAME/envs/" --jobs 1


after_failure:
    - cat data/db/hmmpress_pfama.log
    - find results -name "*.log" -type f | xargs ls -tr | xargs tail -n+2
