dist: trusty

language: bash

apt_addons:
    - build-essential
    - curl
    - git

cache:
    folders:
        - data/download/
        - data/db/
        - $HOME/miniconda3/

before_install:
  - sudo apt-get -qq update
  - curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b
  - export PATH="/home/travis/miniconda3/bin:$PATH"

script:
  - bash src/install/conda_env.sh
  - source activate smsk_trinotate
  - snakemake -j
