dist: trusty

language: bash

addons:
    apt_packages:
        - build-essential
        - git
        - curl

cache:
    directories:
        - $HOME/download/
        - $HOME/data/download/
        - $HOME/data/db/
        - $HOME/miniconda3/

before_install:
  - bash .travis/travis_before_install.sh
  - export PATH="/home/travis/miniconda3/bin:$PATH"

script:
  - source activate smsk_trinotate
  - travis_wait 30 snakemake -j
