# Execution parameters
---
max_threads: 24

chunks:  # Please use #chunks < #sequences
    transdecoder: 4  # Same for blastx and hmmscan
    trinotate: 4

trinotate:
    evalue: 1e-5
    pfam_cutoff: DNC
    rnammer:
        rnammer_path: ./src/rnammer-1.2/rnammer  # Modify this
        org_type: euk  # arc|bac|euk
