# Execution parameters
---
chunks:  # Please use #chunks < #sequences
    transdecoder: 12  # Same for blastx and hmmscan
    trinotate: 12

trinotate:
    evalue: 1e-5
    pfam_cutoff: DNC
    rnammer:
        rnammer_path: ./src/rnammer-1.2/rnammer  # Modify this
        org_type: euk  # arc|bac|euk
