assembly:
    transcript.fa

number_of_chunks: # Please use #chunks < #sequences
    transdecoder: 1 # Same for blastx and hmmscan
    trinotate: 1

db:
    swissprot:
        ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.dat.gz
    NOG.annotations:
        http://eggnogdb.embl.de/download/latest/data/NOG/NOG.annotations.tsv.gz
    obo:
        http://purl.obolibrary.org/obo/go/go-basic.obo
    Pfam-A:
        ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz

trinotate:
    evalue: 1e-5
    pfam_cutoff: DNC
